'''
This script generates arrays of integers of sizes from 1000 to 10,000,000. 
The arrays are saved in a folder named 'arrays' in the same directory as this script. 
The arrays are generated by creating a list of numbers from 1 to the current size, shuffling the list to randomize the order, and then writing the shuffled list to a text file. The file name is 'array_<size>.txt', where <size> is the size of the array. For example, the file name for an array of size 1000 will be 'array_1000.txt'.
'''

import os
import random

# Folder where the arrays will be saved
output_folder = 'arrays'
os.makedirs(output_folder, exist_ok=True)

# Generate arrays of sizes from 1000 to 10,000,000
start_size = 1000
end_size = 10000000
multiplier = 10

size = start_size
while size <= end_size:
    # Generate an array of the current size with numbers from 1 to size
    array = list(range(1, size + 1))
    random.shuffle(array)  # Shuffle the array to randomize order
    
    # Define the file path
    file_path = os.path.join(output_folder, f'array_{size}.txt')
    
    # Write the array to the file
    with open(file_path, 'w') as file:
        file.write('\n'.join(map(str, array)))
    
    print(f'Array of size {size} written to {file_path}')
    
    # Increase size by a multiple of 10
    size *= multiplier

print('All arrays generated and saved.')
